two=(input('двухзначное число='))
three=(input('трехзначное число='))
sum_two=int(two[0])+int(two[1])
mul_two=int(two[0])*int(two[1])
sum_three=int(three[0])+int(three[1])+int(three[2])
mul_three=int(three[0])*int(three[1])*int(three[2])
print('Сумма цифр двухзначного числа =', sum_two)
print('Произведение цифр двухзначного числа =', mul_two)
print('Сумма цифр трехзначного числа =', sum_three)
print('Произведение цифр трехзначного числа =', mul_three)
